### PR TITLE
m is the default export from mithril, so `import m from mithril`

### PR DESCRIPTION
**Pull request by saulrh**
The error seems to get swallowed somewhere in mithril, I'm not sure where or why.

### CODE REVIEW

**Comment by cmcaine** [comment]
You must have a slightly different tsconfig for this to work for you.

Perhaps your tsconfig says `esModuleInterop`: true or something?

**Comment by saulrh** [comment]
...Odd. Our `tsconfig.json` is checked in, so it can't be a configuration change there. I actually can't get it to run at all without making this change. Here's what I get with a completely fresh checkout followed by invoking `yarn install` and `node_modules/.bin/webpack`:

```
ERROR in [at-loader] ./src/components/input.ts:1:8
    TS1192: Module '"/home/saul/src/tridactyl-2-experiments/node_modules/@types/mithril/index"' has no default export.

ERROR in [at-loader] ./src/components/iframe.ts:1:8
    TS1192: Module '"/home/saul/src/tridactyl-2-experiments/node_modules/@types/mithril/index"' has no default export.

ERROR in [at-loader] ./src/content.ts:3:8
    TS1192: Module '"/home/saul/src/tridactyl-2-experiments/node_modules/@types/mithril/index"' has no default export.
```

What versions of `node` and `yarn` are you running?

```
saul@mars ~/s/tridactyl-2-experiments> node --version
v12.3.1
saul@mars ~/s/tridactyl-2-experiments> yarn --version
1.12.3
```

**Comment by saulrh** [comment]
Okay, there's something strange going on here.

**Comment by saulrh** [comment]
I'm not sure what's going on there. Nuking `dist` and `node_modules` fixed it.

**Pull request closed without merging**
